# LegitCheck Configuration

# The location where players are teleported when they are checked.
# This will be saved automatically when you set it in-game using the command.
check-location:
  world: ""
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
